name: Build

on:
  push:
    branches:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: |
          nuget restore MCLauncher.sln

      - name: Build Solution
        run: |
          msbuild MCLauncher.sln /p:Configuration=Release

      - name: Archive build output
        if: success()
        run: |
          mkdir output
          copy /Y YourProject\bin\Release\*.* output\

      - name: Upload build-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output
